#!/bin/bash
set -eu

export EXTENSION_LOCATION="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

if [ ! -z ${1+x} ]; then
    if [ "$1" = "install" ]; then
        pipenv install --system
        exit 0
    fi
fi

python $EXTENSION_LOCATION/summary.py $@
