#!/bin/bash
set -eu

export EXTENSION_LOCATION="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

if [ ! -z ${1+x} ]; then
    if [ "$1" = "install" ]; then
        pip install pipenv
        pipenv install --system

        echo "Installed dependencies!"
        exit 0
    fi
fi

if [[ $OSTYPE = "msys" ]]; then
    py.exe "$EXTENSION_LOCATION\\summary.py" $@
else
    python3 $EXTENSION_LOCATION/summary.py $@
fi
